[tool.poetry]
name = "cumulio"
version = "0.1.1"
description = "Cumulio Pthon SDK for the Core API"
authors = ["Tuana Celik <tuana@cumul.io>"]
readme = "README.md"
homepage = "https://github.com/cumulio/cumulio-sdk-python"
repository = "https://github.com/cumulio/cumulio-sdk-python"
exclude = ["test/*"]
include = ["LICENSE"]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]
packages = [
    { include = "cumulio"}
]

[tool.poetry.scripts]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
